src: fix format string warnings when building for 32bit architectures
Building currently gives the following warnings (which fails the build
because of Werror) about format string mismatches:

src/tpm2-totp.c:343:23: error: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Werror=format=]
         printf("%s%06ld", timestr, totp);
                   ~~~~^            ~~~~
                   %06lld

src/libtpm2-totp.c: In function ‘tpm2totp_generateKey’:
src/libtpm2-totp.c:172:13: error: format ‘%li’ expects argument of type ‘long int’, but argument 3 has type ‘size_t’ {aka ‘unsigned int’} [-Werror=format=]
         dbg("Calling Esys_GetRandom for %li bytes", SECRETLEN - *secret_size);
                                         ~~^
                                         %i

Fix it by using PRIu64 from inttypes.h for uint64_t and %zu for size_t.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>