build: add -O2 to compiler flags required for fortification
If optimisation is not enabled and AX_ADD_FORTIFY_SOURCE is used,
compilation fails with the error

/usr/include/features.h:382:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  382 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~

Signed-off-by: Jonas Witschel <diabonas@gmx.de>